from setuptools import find_packages, setup

package_name = 'rviz_description'

setup(
    name=package_name,
    version='0.0.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        ('share/' + package_name + '/config', ['config/car_urdf.rviz']),
        ('share/' + package_name + '/urdf', ['urdf/car.urdf.xacro']),
        ('share/' + package_name + '/env-hooks', ['env-hooks/car.dsv']),
        ('share/' + package_name + '/launch', ['launch/car_rviz.launch.py', 'launch/simulate.launch.xml']),
        ('share/' + package_name + '/meshes', ['meshes/40mm_standoff.stl']),
        ('share/' + package_name + '/meshes', ['meshes/base_plate.stl']),
        ('share/' + package_name + '/meshes', ['meshes/a01.stl']),
        ('share/' + package_name + '/meshes', ['meshes/lidar_hat.stl']),
        ('share/' + package_name + '/meshes', ['meshes/servo_horn.stl']),
        ('share/' + package_name + '/meshes', ['meshes/a07.stl']),
        ('share/' + package_name + '/meshes', ['meshes/cover_plate.stl']),
        ('share/' + package_name + '/meshes', ['meshes/b01.stl']),
        ('share/' + package_name + '/meshes', ['meshes/a09.stl']),
        ('share/' + package_name + '/meshes', ['meshes/b12-t.stl']),
        ('share/' + package_name + '/meshes', ['meshes/servo_drive_mount.stl']),
        ('share/' + package_name + '/meshes', ['meshes/b08-t.stl']),
        ('share/' + package_name + '/meshes', ['meshes/b07-t.stl']),
        ('share/' + package_name + '/meshes', ['meshes/c08.stl']),
        ('share/' + package_name + '/meshes', ['meshes/c07.stl']),
        ('share/' + package_name + '/meshes', ['meshes/part_2.stl']),
        ('share/' + package_name + '/meshes', ['meshes/c02.stl']),
        ('share/' + package_name + '/meshes', ['meshes/b13-t.stl']),
        ('share/' + package_name + '/meshes', ['meshes/a08.stl']),
        ('share/' + package_name + '/meshes', ['meshes/b06.stl']),
        ('share/' + package_name + '/meshes', ['meshes/jetson_retainer.stl']),
        ('share/' + package_name + '/meshes', ['meshes/b03.stl']),
        ('share/' + package_name + '/meshes', ['meshes/d3542_outrunner.stl']),
        ('share/' + package_name + '/meshes', ['meshes/d3542_outrunner.stl']),
        ('share/' + package_name + '/meshes', ['meshes/b05.stl']),
        ('share/' + package_name + '/meshes', ['meshes/b04.stl']),
        ('share/' + package_name + '/meshes', ['meshes/standoff.stl']),
        ('share/' + package_name + '/meshes', ['meshes/standoff-_copy.stl']),
        ('share/' + package_name + '/meshes', ['meshes/b02.stl']),
        ('share/' + package_name + '/meshes', ['meshes/b09.stl']),
        ('share/' + package_name + '/meshes', ['meshes/b10-t.stl']),
        ('share/' + package_name + '/meshes', ['meshes/b11-t.stl']),
        ('share/' + package_name + '/meshes', ['meshes/wheel_110mm.stl']),
        ('share/' + package_name + '/meshes', ['meshes/camera.stl']),
        ('share/' + package_name + '/meshes', ['meshes/d435.stl']),
        ('share/' + package_name + '/meshes', ['meshes/realsense_mount.stl']),
        ('share/' + package_name + '/meshes', ['meshes/camera_mount.stl']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='scferro',
    maintainer_email='stephencferro@gmail.com',
    description='A package to show the autonomous car in RViz.',
    license='MIT',
    tests_require=['pytest'],
    entry_points={
        
    },
)
